name: CI/CD Pipeline - Master Workflow - Build and deploy to production
on:
  pull_request:
    branches:
      - master

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:unit

      - name: Run integration tests
        run: npm run test:integration

      - name: Run end-to-end tests
        run: npm run test:e2e

      - name: Run migrations
        run: npm run typeorm:run-migration:prod
  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'marceloedudev',
              repo: 'deployments',
              workflow_id: 'main.workflow.yml',
              ref: 'master'
            })
