version: "3"
services:
    order-postgresdb:
        image: postgres:13-alpine
        container_name: "order-postgresdb"
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password123
            - POSTGRES_DB=orderdb
        networks:
            - server_network

networks:
    server_network:
        driver: bridge
