image: node:16.17.1

variables:
  MY_TRIGGER_TOKEN: $MY_TRIGGER_TOKEN

stages:
  - build
  - test
  - deploy

.only-base: &only-base
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || ($CI_PIPELINE_SOURCE == 'merge_request_event' && ( $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" ))

.only-production: &only-production
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"

install_dependencies:
  <<: *only-base
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test_unit:
  <<: *only-base
  stage: test
  needs:
    - install_dependencies
  script:
    - npm run test:unit

test_integration:
  <<: *only-base
  stage: test
  needs:
    - install_dependencies
    - test_unit
  script:
    - npm run test:integration

test_e2e:
  <<: *only-base
  stage: test
  needs:
    - install_dependencies
    - test_integration
  script:
    - npm run test:e2e

publish:
  <<: *only-production
  stage: deploy
  needs:
    - test_e2e
  script:
    - echo "Build and push image to Amazon ECR"
  environment: production

deploy:
  <<: *only-production
  stage: deploy
  needs:
    - publish
  script:
    - 'curl -X POST --fail -F token=$MY_TRIGGER_TOKEN -F ref=master "https://gitlab.com/api/v4/projects/43580268/trigger/pipeline"'
  environment: production
