global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'quarkus-order-service-consumer'
    metrics_path: '/q/metrics'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8080', 'order-service-producer:8080']
