name: CI/CD Pipeline - Master Workflow - Build and deploy to production
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Config Context
        run: echo "Hello World"
