version: "3"
services:
    rabbitmq:
        image: rabbitmq:3.8-management-alpine
        container_name: "rabbitmq"
        environment:
            - RABBITMQ_DEFAULT_USER=master
            - RABBITMQ_DEFAULT_PASS=1234dev
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ~/.docker/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - server_network

networks:
    server_network:
        driver: bridge
