version: "3"
services:
    stock-postgresdb:
        image: postgres:13-alpine
        container_name: "stock-postgresdb"
        restart: always
        ports:
            - 5436:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password123
            - POSTGRES_DB=stockdb
        networks:
            - server_network

networks:
    server_network:
        driver: bridge
