name: CI/CD Pipeline - Master Workflow - Build and deploy to production
on:
  pull_request:
    branches:
      - master

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -X -e -B install -DskipTests --file pom.xml
      - name: Run unit tests
        run: mvn -Dtest=*/unit/** test
      - name: Run integration tests
        run: mvn -Dtest=*/integration/** test
      - name: Run e2e tests
        run: mvn -Dtest=*/e2e/** test
  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'marceloedudev',
              repo: 'deployments',
              workflow_id: 'main.workflow.yml',
              ref: 'master'
            })
